sudo: false

language:
  - node_js
  - objective-c

node_js:
  - "8"

xcode_project: ios/SyrNative/SyrNative.xcodeproj # path to your xcodeproj folder
xcode_scheme: SyrNativeUnitTest

cache:
  directories:
    - node_modules

# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

jobs:
  include:
    - stage: Javascript
      script:
        - npm run test
        - npm run build

# Necessary to compile native modules for io.js v3 or Node.js v4
env:
  - CXX=g++-4.8

after_success:
  - npm run coverage

# Necessary to compile native modules for io.js v3 or Node.js v4
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8