matrix:
  include:
    - language: node_js
      node_js: "8"
      cache:
        directories:
          - node_modules
      before_install:
          - export CHROME_BIN=chromium-browser
          - export DISPLAY=:99.0
          - sh -e /etc/init.d/xvfb start
      install:
        - npm install
      script:
        - npm run test
        - npm run build
      env:
        - CXX=g++-4.8
      after_success:
        - npm run coverage

    - language: objective-c
      os: osx
      osx_image: xcode9.2
      xcode_project: ios/SyrNative/SyrNative.xcodeproj # path to your xcodeproj folder
      script:
        - xcodebuild test -project ios/SyrNative/SyrNative.xcodeproj -scheme SyrNativeUnitTests -destination 'platform=Simulator,name=iPhone 8,OS=11.1'
